export const MAGIC = {
  payloadUrl: 'magic-words/payload.json',
  fetchTimeoutMs: 5000,
  transition: {
    minHoldMs: 420,
    exitDuration: 0.36,
    exitScale: 0.985,
    pulseDuration: 1.4,
  },
  sequence: {
    rowEntrance: 0.42,
    charsPerSecond: 52,
    holdAfterMessageMs: 260,
    finalHoldMs: 420,
    autoScroll: 0.28,
    minRevealDuration: 0.35,
    entrance: {
      bubbleSlide: 18,
      avatarSlide: 10,
      speakerSlide: 6,
      initialScale: 0.985,
      avatarInitialScale: 0.88,
      fadeIn: 0.18,
      avatarDuration: 0.34,
      avatarScaleDuration: 0.38,
      speakerDuration: 0.24,
      speakerDelay: 0.08,
      bubbleDuration: 0.32,
      bubbleDelay: 0.04,
    },
  },
  shell: {
    maxWidth: 640,
    maxHeight: 980,
    aspectRatio: 0.69,
    minInset: 8,
    padding: 18,
    rowGap: 14,
    hintOffsetY: 16,
    emptyStateOffsetY: 40,
    shadow: {
      offsetX: 12,
      offsetY: 18,
      shrinkW: 10,
      shrinkH: 8,
      outerRadius: 34,
      outerAlpha: 0.1,
      innerOffsetX: 10,
      innerOffsetY: 12,
      innerShrinkW: 18,
      innerShrinkH: 16,
      innerRadius: 32,
    },
  },
  input: {
    dragThresholdPx: 6,
  },
  avatar: {
    size: 40,
    gap: 10,
    topOffset: 2,
    shadowOffsetX: 2,
    shadowOffsetY: 3,
    shadowAlpha: 0.12,
    shadowInset: 1,
    fillInset: 3,
    photoInset: 5,
  },
  bubble: {
    minWidth: 140,
    maxWidth: 404,
    paddingX: 14,
    paddingY: 11,
    nameplateGap: 4,
    shadowOffsetX: 1,
    shadowOffsetY: 3,
    shadowShrink: 2,
    shadowRadius: 18,
    shadowAlpha: 0.08,
  },
  curtain: {
    cardMinWidth: 260,
    cardMaxWidth: 340,
    cardWidthRatio: 0.3,
    cardHeight: 180,
    cardCenterOffsetY: 18,
    glowScale: 0.5,
    titleOffsetY: 56,
    subtitleOffsetY: 88,
    statusPaddingBottom: 42,
    statusMaxWidth: 220,
    statusShrink: 70,
    statusHeight: 34,
    scrimAlpha: 0.88,
    glowAlpha: 0.07,
  },
  text: {
    speakerFontSize: 16,
    messageFontSize: 18,
    messageLineHeight: 22,
    hintFontSize: 16,
    emptyStateFontSize: 16,
    transitionTitleFontSize: 22,
    transitionSubtitleFontSize: 16,
    transitionStatusFontSize: 12,
    emojiSize: 20,
  },
  palette: {
    backgroundBase: 0x0b0d10,
    backgroundTop: 0x111419,
    shellTint: 0xf0ede7,
    shellGlow: 0xe72264,
    shellShadow: 0x040506,
    feedWellTint: 0xffffff,
    bubbleLeftTint: 0xf2f4f8,
    bubbleRightTint: 0xf8dce8,
    bubbleShadow: 0x080a0d,
    messageInk: 0x2d343b,
    speakerLeft: 0x617a89,
    speakerRight: 0xe72264,
    screenFrameTint: 0xffffff,
    avatarLeftTint: 0xd6dde3,
    avatarRightTint: 0xf2bfd5,
    scrollTrack: 0xcfd6df,
    scrollThumb: 0xe72264,
    overlayScrim: 0x101215,
    overlayCardTint: 0x20242a,
    overlayStatusTint: 0x333942,
    overlayStatusText: 0xf4f6f8,
    subtitle: 0xa5aeb7,
    hint: 0x7f8992,
  },
  ui: {
    shellInsets: 16,
    bubbleInsets: {
      left: 16,
      top: 10,
      right: 16,
      bottom: 10,
    },
    glassPanelInsets: {
      left: 16,
      top: 16,
      right: 16,
      bottom: 16,
    },
  },
  scroll: {
    minThumbHeight: 52,
    trackWidth: 10,
    trackInset: 8,
    trackAlpha: 0.18,
    thumbAlpha: 1,
    scrollerGap: 10,
  },
  feed: {
    backdropPad: { x: 8, y: 18 },
    backdropAlpha: 1,
    maskRadius: 26,
    frameInset: 10,
    scrollLaneGap: 10,
    scrollLaneOffsetY: -2,
    scrollLaneHeightAdjustment: 4,
    scrollLaneRadius: 8,
    scrollLaneAlpha: 0.08,
    shellShadowAlpha: 0.22,
  },
} as const;
