export const MENU = {
  nineSlice: {
    buttonDepth: { left: 24, top: 14, right: 24, bottom: 14 },
  },
  button: {
    pressY: 3,
  },
  layout: {
    buttonDepthOffsetY: 4,
    bg: { color: 0xf1f2ef },
    logoPattern: {
      tileScale: 0.4,
      alpha: 0.12,
      tileRotation: Math.PI / 7,
      greyscale: 0.82,
      brightness: 0.34,
    },
    logo: {
      widthRatio: 0.36,
      shadowAlpha: 0.28,
      shadowOffset: 6,
      assetWidth: 735,
      assetHeight: 289,
      assetResolution: 2,
    },
    subtitlePlate: {
      minWidth: 280,
      paddingH: 74,
      height: 44,
      radius: 8,
      bgAlpha: 0.42,
    },
    subtitleOffsetY: 176,
    sparkLayerOffsetY: 78,
    button: {
      minWidth: 260,
      maxWidth: 390,
      widthRatio: 0.74,
      height: 66,
      gap: 24,
      startYRatio: 0.48,
    },
    tileDriftSpeed: 0.006,
    tileDriftYFactor: 1.35,
  },
  styles: {
    subtitle: {
      fontSize: 38,
      fontWeight: '700',
    },
    buttonLabel: {
      fontSize: 26,
      fontWeight: '700',
    },
  },
  animation: {
    fadeIn: {
      duration: 0.42,
      ease: 'power2.out',
    },
    title: {
      yPercent: 0.18,
      startY: -180,
      startRotation: -0.1,
      bounceRotation: 0.06,
      startScale: 0.4,
      overshootScale: 1.08,
      dropDuration: 0.38,
      overshootY: 50,
      dropEase: 'power2.out',
      settleSteps: [
        { rotation: -0.025, duration: 0.06 },
        { rotation: 0.015, duration: 0.05 },
        { rotation: 0, duration: 0.07 },
      ],
    },
    bounce: {
      phases: [
        { y: -20, rot: -0.03, squashX: 0.82, squashY: 1.25, dur: 0.14 },
        { y: 15, rot: 0.02, squashX: 1.18, squashY: 0.82, dur: 0.12 },
        { y: -6, rot: -0.012, squashX: 0.94, squashY: 1.08, dur: 0.1 },
        { y: 0, rot: 0, squashX: 1, squashY: 1, dur: 0.08 },
      ],
      settleDuration: 0.28,
      settleEase: 'elastic.out(1, 0.45)',
      impactPhaseIndex: 1,
      squashDurationRatio: 0.8,
    },
    impact: {
      glow: {
        radiusX: 350,
        radiusY: 80,
        color: 0xe72264,
        alpha: 0.3,
        startScale: 0.6,
        targetScale: 1.5,
        duration: 0.4,
        ease: 'power2.out',
        coreRadiusX: 200,
        coreRadiusY: 50,
        coreAlpha: 0.5,
        coreDuration: 0.25,
      },
      rings: {
        waves: [
          {
            radiusX: 420,
            radiusY: 70,
            stroke: 8,
            color: 0xe72264,
            alpha: 0.55,
            startScale: 0.4,
            targetScale: 1.6,
            duration: 0.8,
            ease: 'power2.out',
            delay: 0,
          },
          {
            radiusX: 480,
            radiusY: 80,
            stroke: 5,
            color: 0xed427c,
            alpha: 0.4,
            startScale: 0.35,
            targetScale: 1.45,
            duration: 0.9,
            ease: 'power2.out',
            delay: 0.04,
          },
          {
            radiusX: 540,
            radiusY: 95,
            stroke: 3,
            color: 0xf06695,
            alpha: 0.25,
            startScale: 0.3,
            targetScale: 1.3,
            duration: 1.05,
            ease: 'power2.out',
            delay: 0.08,
          },
        ],
      },
      burst: {
        particlesPerWave: 14,
        frequency: 0.1,
        emitterLifetime: 0.3,
        maxParticles: 35,
        lifetimeMin: 1.8,
        lifetimeMax: 2.8,
        speedStart: 380,
        speedMid: 128,
        speedEnd: 0,
        speedMinMult: 0.6,
        spawnWidth: 850,
        spawnHeight: 70,
        scaleStart: 0,
        scalePeak: 0.65,
        scalePeakTime: 0.05,
        scaleHold: 0.75,
        scaleHoldTime: 0.45,
        scaleEnd: 0.35,
        scaleMinMult: 0.25,
        rotationMin: 200,
        rotationMax: 330,
        rotationSpeed: 50,
      },
    },
    subtitle: {
      startOffsetY: 28,
      startScale: 0.84,
      duration: 0.42,
      delay: 0.45,
      ease: 'elastic.out(1, 0.55)',
    },
    buttons: {
      readyDelay: 1.3,
      completeDelay: 1.7,
      stagger: 0.1,
      startOffsetY: 100,
      rotations: [0.08, -0.06, 0.05],
      startScale: 0.3,
      overshoot: {
        duration: 0.28,
        overshootY: 20,
        scale: 1.15,
        ease: 'back.out(1.5)',
      },
      undershoot: {
        duration: 0.1,
        undershootY: 8,
        scale: 0.92,
        ease: 'power2.out',
      },
      settleBounce: {
        duration: 0.12,
        settleY: 3,
        scale: 1.04,
        ease: 'back.out',
      },
      rest: {
        duration: 0.18,
        ease: 'elastic.out(1, 0.6)',
      },
      glowPulse: {
        scaleX: 1.03,
        scaleY: 0.97,
        duration: 0.8,
        delay: 0.2,
        repeat: 2,
        ease: 'sine.inOut',
      },
    },
  },
} as const;
